DROP TABLE SanPham;
DROP TABLE DanhMuc;
DROP TABLE KhachHang;
DROP TABLE NhanVien;
DROP TABLE HoaDon;


CREATE TABLE DanhMuc (
	TenDanhMuc VARCHAR(255) PRIMARY KEY,
	MoTa VARCHAR(255)
);

CREATE TABLE SanPham (
	MaSP INT(6) NOT NULL PRIMARY KEY,
    TenDanhMuc VARCHAR(50),
    FOREIGN KEY (TenDanhMuc) REFERENCES DanhMuc(TenDanhMuc),
	TenSP VARCHAR(255) NOT NULL,
	GiaBan VARCHAR(255) NOT NULL,
    GiaGoc VARCHAR(255) NOT NULL,
	GioiThieu VARCHAR(255),
    CauHinh VARCHAR(255) NOT NULL,
    HinhAnh VARCHAR(50)
);

CREATE TABLE KhachHang (
	MaKH INT(6) NOT NULL PRIMARY KEY,
    HoVaTen VARCHAR(50)NOT NULL,
	NamSinh DATE NOT NULL,
	GioiTinh VARCHAR(10) NOT NULL,
    SoDienThoai VARCHAR(10) NOT NULL,
    Email VARCHAR(10),
    DiaChi VARCHAR(50)
);

CREATE TABLE NhanVien (
	MaNV INT(6) NOT NULL PRIMARY KEY,
    HoVaTen VARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(50),
    DiaChi VARCHAR (50),
    GioiTinh VARCHAR (10)
);

CREATE TABLE HoaDon (
	MaHD INT(6) NOT NULL PRIMARY KEY,
    MaNV INT(6)NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
	MaKH INT(6),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    TenSP VARCHAR(255) NOT NULL,
    NgayTaoHD DATE,
    GhiTru VARCHAR(50),
    SoTien VARCHAR (50)
);
